# Generated by Django 4.2.8 on 2023-12-18 23:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options_dailyactivity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyactivity',
            name='expected_cn',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Expected C.N.'),
        ),
        migrations.AlterField(
            model_name='dailyactivity',
            name='single_fish_weight',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Single Fish Weight (gm)'),
        ),
    ]
