# Generated by Django 4.2.8 on 2024-01-08 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fish_tanks', '0002_initial'),
        ('projects', '0006_project_undigested_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tank',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='fish_tanks.fishtank'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
