# Generated by Django 4.2.8 on 2024-01-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_tank_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='undigested_percentage',
        ),
    ]
