# Generated by Django 4.2.9 on 2024-01-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_expected_cn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyactivity',
            name='live_fish',
        ),
    ]
