# Generated by Django 4.2.9 on 2024-01-09 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_dailyactivity_undigested_percentage'),
        ('fish_tanks', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishtank',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='fishtank',
            name='height',
        ),
        migrations.RemoveField(
            model_name='fishtank',
            name='length',
        ),
        migrations.RemoveField(
            model_name='fishtank',
            name='width',
        ),
        migrations.AlterField(
            model_name='fishtank',
            name='current_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project', verbose_name='Current Project'),
        ),
    ]
